name: goreleaser

on:
  push:
    tags:
      - *

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
